/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignRouteImport } from './routes/web-design'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as InboundMarketingRouteImport } from './routes/inbound-marketing'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as IndexRouteImport } from './routes/index'

const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundMarketingRoute = InboundMarketingRouteImport.update({
  id: '/inbound-marketing',
  path: '/inbound-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
  '/vendas': typeof VendasRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
  '/vendas': typeof VendasRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercial': typeof ComercialRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
  '/vendas': typeof VendasRoute
  '/web-design': typeof WebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comercial'
    | '/inbound-marketing'
    | '/performance'
    | '/vendas'
    | '/web-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comercial'
    | '/inbound-marketing'
    | '/performance'
    | '/vendas'
    | '/web-design'
  id:
    | '__root__'
    | '/'
    | '/comercial'
    | '/inbound-marketing'
    | '/performance'
    | '/vendas'
    | '/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComercialRoute: typeof ComercialRoute
  InboundMarketingRoute: typeof InboundMarketingRoute
  PerformanceRoute: typeof PerformanceRoute
  VendasRoute: typeof VendasRoute
  WebDesignRoute: typeof WebDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound-marketing': {
      id: '/inbound-marketing'
      path: '/inbound-marketing'
      fullPath: '/inbound-marketing'
      preLoaderRoute: typeof InboundMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComercialRoute: ComercialRoute,
  InboundMarketingRoute: InboundMarketingRoute,
  PerformanceRoute: PerformanceRoute,
  VendasRoute: VendasRoute,
  WebDesignRoute: WebDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
