/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as InboundMarketingRouteImport } from './routes/inbound-marketing'
import { Route as IndexRouteImport } from './routes/index'

const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundMarketingRoute = InboundMarketingRouteImport.update({
  id: '/inbound-marketing',
  path: '/inbound-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbound-marketing': typeof InboundMarketingRoute
  '/performance': typeof PerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inbound-marketing' | '/performance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inbound-marketing' | '/performance'
  id: '__root__' | '/' | '/inbound-marketing' | '/performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboundMarketingRoute: typeof InboundMarketingRoute
  PerformanceRoute: typeof PerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound-marketing': {
      id: '/inbound-marketing'
      path: '/inbound-marketing'
      fullPath: '/inbound-marketing'
      preLoaderRoute: typeof InboundMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboundMarketingRoute: InboundMarketingRoute,
  PerformanceRoute: PerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
